name: Bug-Report
description: Melde ein Bug auf GCRP!
labels: ['Class: bug']

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibe dein Problem!
      description: Beschreibe dein Problem Genau!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduktionsschritte
      description: Beschreibe wie man den Fehler reproduziert.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: Schreibe was normalerweise passieren sollte!
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Zusatz
      description: Screenshots, Videos etc.
  - type: input
    id: os
    attributes:
      label: Betriebsystem
      description: Dein Betriebsystem!
      placeholder: e.g. Windows 10 oder 11 usw.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: On what version is the issue present
      placeholder: e.g. dev/7.0-dev3
    validations:
      required: true
